// Este un ejemplo del array de artículos que le llegaran por props al Slider
// Para renderizar el slider:
// <Slider mostFavoriteArticles={aquiVaElArrayConLosArticulosAmostrar} />

export const mostFavoriteArticles = [
   {
      "id": "659c5144-6f04-4605-81be-0daefd323e6f",
      "title": "Samsung Galaxy S22",
      "rating": 4.4,
      "detail": "Es un kit de nivel profesional que cabe en una mano. La cámara posterior triple y la cámara de selfie ofrecen hardware y software de cámara innovadores para que puedas capturar fácilmente una galería llena de contenido digno de compartir.",
      "marca": "Samsung",
      "modelo": "S22",
      "so": "Android",
      "cpu": "Octa-Core de 2.99GHz",
      "ram": "8GB",
      "color": "Green",
      "pantalla": "6.1",
      "image": "https://http2.mlstatic.com/D_NQ_NP_686082-MLA49387650727_032022-O.webp",
      "stock": 3,
      "disable": false,
      "price": 1593,
      "conectividad": "USB Type-C, USB 3.2 Gen 1",
      "category": "smartphones"
    },
    {
      "id": "513cbbee-afd5-4407-aef5-ef4e085cc905",
      "title": "Samsung Galaxy S21 FE 5G",
      "rating": 4.6,
      "detail": "Ya no volverás a perderte esa toma perfecta. Conocé los Galaxy S21 5G y S21+ 5G. Están diseñados para revolucionar el video y la fotografía, con una resolución cinematográfica de 8K para que puedas tomar fotos épicas mientras hacés un video. Ambos modelos tienen todas las características que necesitás: 64 MP, el conjunto de chips más rápido y una batería increíble que dura todo el día.1 Tu mundo va a ser realmente épico.",
      "marca": "Samsung",
      "modelo": "S21",
      "so": "Android",
      "cpu": "2.9GHz, 2.8GHz, 2.2GHz",
      "ram": "8GB",
      "color": "Gray",
      "pantalla": "6.2",
      "image": "https://http2.mlstatic.com/D_NQ_NP_730981-MLA48800008115_012022-O.webp",
      "stock": 1,
      "disable": false,
      "price": 1291,
      "conectividad": "USB Type-C, USB 3.2 Gen 1",
      "category": "smartphones"
    },
    {
      "id": "c89cb3c0-6adc-4017-8519-411aadca83c8",
      "title": "Samsung Galaxy Z Fold3 5G",
      "rating": 4.6,
      "detail": "Esto es todo lo que querías en un smartphone 5G duradero y de primera calidad. Lo creamos plegable para revelar una enorme pantalla en la que puedas ver, trabajar y divertirte como nunca antes.",
      "marca": "Samsung",
      "modelo": "Fold3",
      "so": "Android",
      "cpu": "2.84GHz, 2.4GHz, 1.8GHz",
      "ram": "12GB",
      "color": "Silver",
      "pantalla": "7.6",
      "image": "https://http2.mlstatic.com/D_NQ_NP_680610-MLA47574356658_092021-O.webp",
      "stock": 7,
      "disable": false,
      "price": 1955,
      "conectividad": "USB Type-C, USB 3.2 Gen 1",
      "category": "smartphones"
    },
    {
      "id": "1dccfe38-e23f-4949-abc7-89c9b758fbd5",
      "title": "Samsung Galaxy S22 Ultra",
      "rating": 4.6,
      "detail": "Conocé el Galaxy S22 Ultra, con el poder del Note. El marco pulido, delgado y audaz, rodea la forma extruida para lograr una simetria elegamte. Y la cámara lineal, acentuada por anillos de lentes espejados, parece flotar en su lugar.",
      "marca": "Samsung",
      "modelo": "S22 Ultra",
      "so": "Android",
      "cpu": "2.99GHz, 2.4GHz, 1.7GHz",
      "ram": "12GB",
      "color": "Green, Black, White, Burgundy",
      "pantalla": "8.9",
      "image": "https://http2.mlstatic.com/D_NQ_NP_668050-MLA49303776893_032022-O.webp",
      "stock": 4,
      "disable": false,
      "price": 2449,
      "conectividad": "USB Type-C, USB 3.2 Gen 1",
      "category": "smartphones"
    },
    {
      "id": "b1c8c793-e422-40e4-b806-bd90aec7eb6a",
      "title": "Samsung Galaxy S21+ 5G",
      "rating": 4.6,
      "detail": "Video de 8K es la resolución más alta en un teléfono inteligente, lo que hace que tu contenido luzca aún mejor que el cine. Y con 8K 24 fps, cada vlog y memoria es tu próxima toma al estrellato. Grabá, cargá y mirá directamente en YouTube.",
      "marca": "Samsung",
      "modelo": "S21+ 5G",
      "so": "Android",
      "cpu": "2.9GHz, 2.8GHz, 2.2GHz",
      "ram": "8GB",
      "color": "Violet",
      "pantalla": "6.2",
      "image": "https://http2.mlstatic.com/D_NQ_NP_908285-MLA50209440689_062022-O.webp",
      "stock": 2,
      "disable": false,
      "price": 1622,
      "conectividad": "USB Type-C, USB 3.2 Gen 1",
      "category": "smartphones"
    },
    {
      "id": "fadd534b-bcaa-4d81-bf2d-7238609f88de",
      "title": "Samsung Galaxy Z Flip3 5G",
      "rating": 4.6,
      "detail": "Se pliega en el bolsillo. Entra en tu cartera. Se desliza en tus jeans más apretados. Cuando lo sacás, se abre un smartphone 5G con pantalla completa que se adapta a tus ángulos favoritos.",
      "marca": "Samsung",
      "modelo": "Flip3",
      "so": "Android",
      "cpu": "2.84GHz, 2.4GHz, 1.8GHz",
      "ram": "8GB",
      "color": "Black",
      "pantalla": "6.7",
      "image": "https://http2.mlstatic.com/D_NQ_NP_618327-MLA48897052450_012022-O.webp",
      "stock": 3,
      "disable": false,
      "price": 1955,
      "conectividad": "USB Type-C, USB 2.0",
      "category": "smartphones"
    },
    {
      "id": "7202765c-7d22-4b56-81e8-f3eddd1501bf",
      "title": "Samsung Z Flip4",
      "rating": 4.2,
      "detail": "Elegí un color que combine con todo, pero que no se parezca a nada. Un acabado opaco en el vidrio crea un contraste suave con el marco de metal brillante. Seleccioná entre cuatro tonos: Bora Purple, Graphite, Pink Gold y Blue.",
      "marca": "Samsung",
      "modelo": "Flip4",
      "so": "Android",
      "cpu": "2.99GHz, 2.4GHz, 1.7GHz",
      "ram": "12GB",
      "color": "Bora Purple, Graphite, Pink y Blue",
      "pantalla": "7.3",
      "image": "https://http2.mlstatic.com/D_NQ_NP_624071-MLA47717269574_092021-O.webp",
      "stock": 3,
      "disable": false,
      "price": 1593,
      "conectividad": "USB Type-C, USB 3.2 Gen 1",
      "category": "smartphones"
    },
    {
      "id": "7ca7b809-d778-44e6-a06a-dce7dafea457",
      "title": "Samsung Galaxy Z Fold2",
      "rating": 4.7,
      "detail": "Conocé el smartphone que está cambiando la forma del futuro. El número uno del mundo en plegables, este smartphone de última generación pone en la palma de tu mano un potente rendimiento, cristal plegable y una batería para todo el día",
      "marca": "Samsung",
      "modelo": "Fold2",
      "so": "Android",
      "cpu": "Octa-Core de 3.09GHz, 2.4GHz, 1.8GHz",
      "ram": "12GB",
      "color": "Green, Bronce",
      "pantalla": "7.6",
      "image": "https://images.samsung.com/is/image/samsung/p6pim/ar/sm-f916bznqaro/gallery/ar-galaxy-z-fold2-f916-341065-sm-f916bznqaro-thumb-344960155?$160_160_PNG$",
      "stock": 10,
      "disable": false,
      "price": 2449,
      "conectividad": "USB Type-C, USB 3.2 Gen 1",
      "category": "smartphones"
    }
]