// Este un ejemplo del array de artículos que le llegaran por props al Slider
// Para renderizar el slider:
// <Slider mostFavoriteArticles={aquiVaElArrayConLosArticulosAmostrar} />

export const mostFavoriteArticles = [
   {
      "id": "34f483ca-beb0-4671-a940-54e0090ea8a5",
      "title": "Samsung Galaxy S22",
      "rating": 4.4,
      "detail": "Es un kit de nivel profesional que cabe en una mano. La cámara posterior triple y la cámara de selfie ofrecen hardware y software de cámara innovadores para que puedas capturar fácilmente una galería llena de contenido digno de compartir.",
      "marca": "Samsung",
      "modelo": "S22",
      "so": "Android",
      "cpu": "Octa-Core de 2.99GHz",
      "ram": "8GB",
      "color": "Green",
      "pantalla": "6.1",
      "image": "https://http2.mlstatic.com/D_NQ_NP_686082-MLA49387650727_032022-O.webp",
      "stock": 3,
      "disable": false,
      "price": 1593,
      "conectividad": "USB Type-C, USB 3.2 Gen 1",
      "category": "smartphones"
   },
   {
      "id": "a57babbe-50b4-4263-a1bd-b40f0bb881ed",
      "title": "Apple iPhone 8 Plus Plata De 128gb",
      "rating": 4.5,
      "detail": "El dispositivo cuenta con cámara frontal de 7 Mpx para que puedas sacarte divertidas selfies o hacer videollamadas. Con su pantalla IPS de 5.5\", disfruta de colores intensos y mayor nitidez en todos tus contenidos. Su memoria ram de 3 GB permite que tu smartphone funcione de manera fluida y sin demoras al realizar distintas tareas, jugar o navegar. Con el sensor de huella digital, el acceso es seguro y podrás desbloquearlo automáticamente con un toque. Con su memoria interna de 128 GB podrás almacenar archivos y aplicaciones de gran tamaño sin necesidad de subirlos a la nube y aprovechar tus momentos sin conexión para darles el máximo uso.",
      "marca": "Apple",
      "modelo": "iPhone 8 Plus",
      "so": "iOS 11",
      "cpu": "Apple A11 Bionic",
      "ram": "4 GB",
      "color": "Negro",
      "pantalla": "6.1\"",
      "image": "https://http2.mlstatic.com/D_NQ_NP_933513-MLA44156542321_112020-O.webp",
      "stock": 11,
      "disable": false,
      "price": 529.99,
      "conectividad": "4G/LTE",
      "category": "smartphones"
   },
   {
      "id": "2f3744eb-e5c8-4357-9627-7c4eef59a931",
      "title": "Xiaomi Pocophone Poco X4 Pro 5G Dual SIM 128 GB laser black 6 GB ram",
      "rating": 4,
      "detail": "Fotografía profesional en tu bolsillo. Descubrí infinitas posibilidades para tus fotos con las 3 cámaras principales de tu equipo. Poné a prueba tu creatividad y jugá con la iluminación, diferentes planos y efectos para obtener grandes resultados. Además, el dispositivo cuenta con cámara frontal de 20 Mpx para que puedas sacarte divertidas selfies o hacer videollamadas. Mirá tus series y películas favoritas con la mejor definición a través de su pantalla AMOLED de 6.67 pulgadas. Disfrutá de colores brillantes y detalles precisos en todos tus contenidos.",
      "marca": "Xiaomi",
      "modelo": "Poco X4 Pro 5G",
      "so": "Android 11",
      "cpu": "2x2.2 GHz Kryo 660 Gold",
      "ram": "6 GB",
      "color": "Black",
      "pantalla": "6.67",
      "image": "https://http2.mlstatic.com/D_NQ_NP_2X_782725-MLA49423195235_032022-F.webp",
      "stock": 7,
      "disable": false,
      "price": 469,
      "conectividad": "5G",
      "category": "smartphones"
   },
   {
      "id": "c44651cf-316f-4d84-b9a3-276c7318a8b1",
      "title": "Laptop Inspiron 3501",
      "rating": 4.2,
      "detail": "Cuenta con una pantalla de borde estrecho no táctil antirreflejo con retroiluminación LED, con disco solido de alta velocidad que combinada con su procesador y memoria ram, la hacen la opcion perfecta de compra",
      "marca": "Dell",
      "modelo": "Inspiron",
      "so": "windows 10",
      "cpu": "Intel Core i3",
      "ram": "8 gb",
      "color": "Silver",
      "pantalla": "15.6",
      "image": "https://m.media-amazon.com/images/I/61kwF967nJL._AC_SX522_.jpg",
      "stock": 7,
      "disable": false,
      "price": 549.95,
      "conectividad": "Wi-Fi",
      "category": "notebooks"
   },
   {
      "id": "210304c9-0a2b-4235-ad5b-7f27590f859f",
      "title": "Apple Watch - Serie 7 con GPS y caja de aluminio color rojo de 1.61 pulgadas con correa deportiva color rojo, tamaño regular",
      "rating": 3.7,
      "detail": "Monitor de actividad, monitor de ritmo cardíaco, monitor de sueño, oxígeno en sangre.",
      "marca": "Apple",
      "modelo": "Apple Watch Series 7",
      "so": "",
      "cpu": "",
      "ram": "",
      "color": "Pink",
      "pantalla": "4",
      "image": "https://m.media-amazon.com/images/I/711BW6zqs0L._AC_SX679_.jpg",
      "stock": 12,
      "disable": false,
      "price": 315.84,
      "conectividad": "USB",
      "category": "accesories"
   },
   {
      "id": "aa961bb2-5edb-41cd-82eb-2d4ec0611418",
      "title": "MSI GL66 - Laptop para Juegos",
      "rating": 5,
      "detail": "Gran pantalla de 15.6 pulgadas con imagenes realistas de actualización rapida, gran potencia para enfrentarse a cualquier juego y aplicación, con teclas personalizadas.",
      "marca": "Acer",
      "modelo": "Pulse GL66 11UGK-001",
      "so": "windows 10 Home",
      "cpu": "Intel Core i7",
      "ram": "16 gb",
      "color": "Black",
      "pantalla": "15.6",
      "image": "https://m.media-amazon.com/images/I/61Ze2wc9nyS._AC_SX522_.jpg",
      "stock": 12,
      "disable": false,
      "price": 1899,
      "conectividad": "Wi-Fi",
      "category": "notebooks"
   },
   {
      "id": "2d6f8455-4701-4b9e-b27a-64e2797435b9",
      "title": "Laptop Latitude E5400",
      "rating": 4,
      "detail": "Equipo con un procesador intel de 8a generacion, lo que la hace rendidora para trabajar en la escuela u oficina, Memoria ram mayor a las del mercado",
      "marca": "Dell",
      "modelo": "Latitude E5400",
      "so": "windows 10 pro",
      "cpu": "Intel Core i7-8665U",
      "ram": "16 gb",
      "color": "Gray",
      "pantalla": "14",
      "image": "https://m.media-amazon.com/images/I/61DocMRdvyL._AC_SX522_.jpg",
      "stock": 19,
      "disable": false,
      "price": 352.55,
      "conectividad": "Wi-Fi",
      "category": "notebooks"
   },
   {
      "id": "c44651cf-316f-4d84-b9a3-276c7318a8b1",
      "title": "Laptop Inspiron 3501",
      "rating": 4.2,
      "detail": "Cuenta con una pantalla de borde estrecho no táctil antirreflejo con retroiluminación LED, con disco solido de alta velocidad que combinada con su procesador y memoria ram, la hacen la opcion perfecta de compra",
      "marca": "Dell",
      "modelo": "Inspiron",
      "so": "windows 10",
      "cpu": "Intel Core i3",
      "ram": "8 gb",
      "color": "Silver",
      "pantalla": "15.6",
      "image": "https://m.media-amazon.com/images/I/61kwF967nJL._AC_SX522_.jpg",
      "stock": 7,
      "disable": false,
      "price": 549.95,
      "conectividad": "Wi-Fi",
      "category": "notebooks"
   },
   {
      "id": "72304607-34d1-43d7-a790-251fe5b05b00",
      "title": "HP Laptop 15-eh0003la",
      "rating": 5,
      "detail": "Una portátil con un rendimiento impresionante. Batería de larga duración incorporada, prestaciones de procesamiento multipleLa DDR4, diseñada para funcionar con más eficiencia y confiabilidad a mejores velocidades",
      "marca": "HP",
      "modelo": "15-eh0003la",
      "so": "windows 11 Home",
      "cpu": "AMD Ryzen 7",
      "ram": "16 gb",
      "color": "Gold",
      "pantalla": "15.6",
      "image": "https://images-na.ssl-images-amazon.com/images/I/51uL8Dgxe7S.__AC_SY300_SX300_QL70_ML2_.jpg",
      "stock": 7,
      "disable": false,
      "price": 974.95,
      "conectividad": "Wi-Fi",
      "category": "notebooks"
   }
]